"""Add reversal statistics columns

Revision ID: c8515d369ff9
Revises: 002
Create Date: 2026-03-03 09:14:25.801709
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c8515d369ff9'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_sessions', sa.Column('reversal_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reconciliation_sessions', sa.Column('total_reversal_amount', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_sessions', 'total_reversal_amount')
    op.drop_column('reconciliation_sessions', 'reversal_count')
    # ### end Alembic commands ###
